In [3]:
# Array - Numpy Python Tutorial

#######################################################

import numpy as np

some_list = [1,2,3,4,5]

print(some_list)

some_np_list = np.array(some_list)

print(some_np_list)

#######################################################

some_list = [i for i in range(10)]

print(some_list)

some_np_list = np.arange(10)

print(some_np_list)

some_np_list2 = np.array([2,3,4,5,6])

print(some_np_list2)

some_np_list3 = np.arange(0,11,2)

print(some_np_list3)

#######################################################

some_list = [i for i in range(10)]

print(some_list)

print(some_list[1])

some_np_list = np.arange(10)

print(some_np_list)

print(some_np_list[1])

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[ 0  2  4  6  8 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1
[0 1 2 3 4 5 6 7 8 9]
1
