In [6]:
# Broadcasting - Numpy Python Tutorial

#######################################################

import numpy as np

A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

B = np.matrix([[100,100,100],[100,100,100],[100,100,100]])

print(A)

print(B)

print(A + B)

print(A - B)

C = np.matrix([100,100,100])

print(A + C)

print(A - C)

D = np.matrix([100])

print(A + D)

print(A - D)

#######################################################

print(A * B)
print(A / B)

print(np.tile(C,(3,1)))

print(A * np.tile(C,(3,1)))

print(A / np.tile(C,(3,1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[-99 -98 -97]
 [-96 -95 -94]
 [-93 -92 -91]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[-99 -98 -97]
 [-96 -95 -94]
 [-93 -92 -91]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[-99 -98 -97]
 [-96 -95 -94]
 [-93 -92 -91]]
[[ 600  600  600]
 [1500 1500 1500]
 [2400 2400 2400]]
[[0.01 0.02 0.03]
 [0.04 0.05 0.06]
 [0.07 0.08 0.09]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]
[[ 600  600  600]
 [1500 1500 1500]
 [2400 2400 2400]]
[[0.01 0.02 0.03]
 [0.04 0.05 0.06]
 [0.07 0.08 0.09]]
