In [3]:
# Linear Algebra - Numpy Python Tutorial

#######################################################

import numpy as np

matrix_a = np.matrix([1,2,3])

matrix_b = np.matrix([11,12,13])

print(matrix_a)
print(matrix_b)

vector_dot_product = np.vdot(matrix_a,matrix_b)

print(vector_dot_product)

matrix_c = np.matrix([[1,2,3],[4,5,6]])

matrix_d = np.matrix([[11,12],[13,14],[15,16]])

print(matrix_c)
print(matrix_d)

matrix_dot_product = np.dot(matrix_c,matrix_d)

print(matrix_dot_product)

print(matrix_c.shape)
print(matrix_d.shape)

#######################################################

# A x X = B

a = np.matrix([[1,2],[3,4]])
b = np.matrix([[9,8],[7,6]])

print(a)
print(b)

x = np.linalg.solve(a,b)

print(x)

print(a * x)

#######################################################

some_matrix = np.matrix([[1,2],[3,4]])

some_matrix_inverse = np.linalg.inv(some_matrix)

print(some_matrix_inverse)

print((some_matrix * some_matrix_inverse).round(0))

[[1 2 3]]
[[11 12 13]]
[[11]]
[[1 2 3]
 [4 5 6]]
[[11 12]
 [13 14]
 [15 16]]
[[ 82  88]
 [199 214]]
(2, 3)
(3, 2)
[[1 2]
 [3 4]]
[[9 8]
 [7 6]]
[[-11. -10.]
 [ 10.   9.]]
[[9. 8.]
 [7. 6.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]
