In [4]:
# Matrices - Numpy Python Tutorial

#######################################################

import numpy as np

matrix_a = np.matrix([[1,3,5],[7,9,11],[13,15,17]])

matrix_b = np.matrix([[2.0,4.0,6.0],[8.0,10.0,12.0],[14.0,16.0,18.0]])

print(matrix_a)

print(matrix_b)

#######################################################

matrix_add = matrix_a + matrix_b

print(matrix_add)

matrix_subtract = matrix_a - matrix_b

print(matrix_subtract)

matrix_multiply = matrix_a * matrix_b

print(matrix_multiply)

matrix_divide = matrix_a - matrix_b

print(matrix_divide)

matrix_3X = matrix_a * 3

print(matrix_3X)

#######################################################

print(matrix_a.shape)

print(matrix_a.dtype)
print(matrix_b.dtype)

print(matrix_a.size)

print(matrix_a.ndim)

matrix_inception = np.array([[[[[[[[[9,9,9]]]]]]]]])

print(matrix_inception.ndim)

print(matrix_inception.shape)

print(matrix_inception.size)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 3.  7. 11.]
 [15. 19. 23.]
 [27. 31. 35.]]
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]
[[ 96. 114. 132.]
 [240. 294. 348.]
 [384. 474. 564.]]
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]
[[ 3  9 15]
 [21 27 33]
 [39 45 51]]
(3, 3)
int64
float64
9
2
9
(1, 1, 1, 1, 1, 1, 1, 1, 3)
3
