In [9]:
# Ndim - Numpy Python Tutorial

#######################################################

some_list = [i for i in range(10)]

some_list = np.array(some_list)

print(some_list)

print(some_list.ndim)

#######################################################

some_list2 = [some_list for i in range(5)]

some_list2 = np.array(some_list2)

print(some_list2)
print(some_list2.ndim)

#######################################################

some_list3 = [some_list2 for i in range(3)]

some_list3 = np.array(some_list3)

print(some_list3)
print(some_list3.ndim)

[0 1 2 3 4 5 6 7 8 9]
1
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
2
[[[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]]
3
