In [5]:
# Reshape - Numpy Python Tutorial

#######################################################

import numpy as np

some_list = np.arange(1,51)

print(some_list)

some_list1 = some_list.reshape(10,5)

some_list2 = some_list.reshape(5,10)

print(some_list1)

print(some_list2)

#######################################################

some_list_matrix = some_list.reshape(2,5,5)

print(some_list_matrix)

#######################################################

list_a, list_b = some_list.reshape(2,5,5)

print(list_a)

print(list_b)

#######################################################

some_list_matrix = some_list.reshape(2,5,5)

print(some_list_matrix)

flatten_list1 = some_list_matrix.reshape(1,50,1)

flatten_list2 = some_list_matrix.reshape(1,1,50)

print(flatten_list1)
print(flatten_list2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 3