In [3]:
# Shape - Numpy Python Tutorial

#######################################################

import numpy as np

some_list = [i for i in range(10)]

some_list = np.array(some_list)

print(some_list)

print(some_list.shape)

#######################################################

some_list2 = [some_list for i in range(5)]

some_list2 = np.array(some_list2)

print(some_list2)

print(some_list2.shape)

#######################################################

some_list3 = [some_list2 for i in range(3)]

some_list3 = np.array(some_list3)

print(some_list3)

print(some_list3.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(5, 10)
[[[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]]
(3, 5, 10)
